<table class="menu_table">
    <tr>
	<td class="menu_right" colspan=3><?php echo $_SESSION["fullname"];?></td>
    </tr><tr>
	<td class="menu_left"><a href="index.php?page=coverlist" class="menu">Žádosti o cover</a></td>
	<td class="menu_left"><a href="index.php?page=pwchange" class="menu">Změna hesla</a></td>
	<td class="menu_right"><a href="logout.php" class="menu">Odhlásit</a></td>
    </tr>
</table>
