<table class="menu_table">
    </tr><tr>
	<td class="menu_left"><a href="index.php?page=welcome" class="menu">Úvod</a></td>
	<td class="menu_left"><a href="index.php?page=coverask" class="menu">Žádost o cover</a></td>
	<td class="menu_left"><a href="index.php?page=edittask" class="menu">Změna žádosti</a></td>
	<td class="menu_left"><a href="index.php?page=kontakt" class="menu">Kontakty</a></td>
	<td class="menu_right"><a href="index.php?page=admin" class="menu">Admin zona</a></td>
    </tr>
</table>
