
<center><h2>11 PRAVIDEL SLUŠNÉHO CHOVÁNÍ</h2></center>

<ul>
<li> Když si o cover zažádáte, prosíme vás o to, abyste dále nežádali o cover někoho jiného. Samozřejmě to neplatí v případě, že jsme cover odmítli, či na něj čekáte déle než 2 týdny. V tom případě nám ale dějte vědět, že už jste se obrátili jinam, ať už cover neděláme. To samé platí i naopak - pokud už jste zažádali o cover jinde, nemá smysl nám psát. Je to neslušné a pro tvůrce dost ponižující, když si vybíráte mezi námi.

<li> Pokud vám cover uděláme, mějte jej na knize alespoň 3 měsíce, pokud není domluveno jinak. Když si změníte přezdívku či název knihy, dokážeme to lehce opravit. Stačí napsat.

<li> Někam připište, kdo vám cover udělal. Třeba do popisku, pod prolog, do vašeho osobního popisu, kamkoli. Důvodem je, že nám covery už mnozí ukradli (vydávání za své je také krádež).

<li> Covery si sami nijak neupravujte, naše vodoznaky nemažte. Pokud jej chcete upravit, dá se to zařídit i normální cestou - kontaktování autora coveru.

<li> Pořádně si rozmyslete, zda knihu vydáte, zda ji nesmažete po dvou kapitolách. Nás to stojí čas a úsilí a taková práce je k ničemu.

<li> Covery na nevydané knížky musí být vydané do měsíce od dokončení coveru. Samozřejmě se dá domluvit i jinak, ale to už záleží na grafikovi.

<li> Zpětná vazba. Pokud se vám cover nelíbí, napište to. My hlavy netrháme. Jen se prostě někdy nepovede dostat se do stylu autora, ale to se dá napravit. Chceme přeci, aby byl zákazník spokojen.

<li> Jestliže se cover rozhodnete přestat používat, oznamte nám to a my z něj utvoříme premade, aby práce nezůstala nevyužitá.

<li> Může se stát, že vašim požadavkům nevyhovíme. Ale věřte nám, někdy to ani nejde (7 lidí na jeden cover, od každého grafika chce cover, aby si mohl vybrat, přidání své vlastní fotky v naprosto nedostatečném rozlišení atd.). Samozřejmě se pokusíme vyhovět vašim požadavkům na vzhled, ale ne vždy je to možné či vhodné. Nevymýšlejte si prosím nesplnitelné úlohy typu - „chci mít na coveru lítající rybu, která je zespodu chlupatá a povídá si s Kájou Gottem".

<li> Vyčkejte. Někdy nám práce trvá déle, protože i my máme osobní život, jsou před vámi další lidé a nebo nás nic v tu dobu nenapadá.

<li> Nezapomeňte na anotaci (popis) příběhu, jinak je velmi těžké se trefit a tvorba trvá zbytečně dlouho. Nebudeme informace hledat někde na vašem účtu, správné vyplnění formuláře je vaše práce.
</ul>



